/**
 * Sample catalog and demo phones for local development and screenshots.
 *
 * The specs below were typed from memory as sample data. Before going live,
 * check each model (Admin → Catalog → "Get specs" or edit by hand) and mark
 * it verified. Prices are examples only.
 */

export type SeedModel = {
  brand: string;
  name: string;
  aliases?: string[];
  os: "iOS" | "Android";
  launchYear: number;
  chipset: string;
  performance: 1 | 2 | 3 | 4;
  displayInches: number;
  displayType: string;
  refreshHz: number;
  mainCameraMp: number;
  cameraSummary: string;
  frontCameraMp: number;
  batteryMah: number;
  chargingW: number;
  has5g: boolean;
  weightG: number;
  variants: { ramGb: number | null; storageGb: number; launchPriceInr: number | null }[];
  /** Shop's buying price for a good-condition unit, per storage size */
  buyPrices?: Record<number, number>;
};

export const SEED_MODELS: SeedModel[] = [
  {
    brand: "Apple",
    name: "iPhone 11",
    aliases: ["A2221", "iphone11"],
    os: "iOS",
    launchYear: 2019,
    chipset: "A13 Bionic",
    performance: 3,
    displayInches: 6.1,
    displayType: "LCD",
    refreshHz: 60,
    mainCameraMp: 12,
    cameraSummary: "12MP + 12MP ultra-wide",
    frontCameraMp: 12,
    batteryMah: 3110,
    chargingW: 18,
    has5g: false,
    weightG: 194,
    variants: [
      { ramGb: null, storageGb: 64, launchPriceInr: 64900 },
      { ramGb: null, storageGb: 128, launchPriceInr: 69900 },
    ],
    buyPrices: { 64: 12500, 128: 14000 },
  },
  {
    brand: "Apple",
    name: "iPhone 12",
    aliases: ["A2403"],
    os: "iOS",
    launchYear: 2020,
    chipset: "A14 Bionic",
    performance: 3,
    displayInches: 6.1,
    displayType: "OLED",
    refreshHz: 60,
    mainCameraMp: 12,
    cameraSummary: "12MP + 12MP ultra-wide",
    frontCameraMp: 12,
    batteryMah: 2815,
    chargingW: 20,
    has5g: true,
    weightG: 164,
    variants: [
      { ramGb: null, storageGb: 64, launchPriceInr: 79900 },
      { ramGb: null, storageGb: 128, launchPriceInr: 84900 },
    ],
    buyPrices: { 64: 16000, 128: 18000 },
  },
  {
    brand: "Apple",
    name: "iPhone 13",
    aliases: ["A2633", "A2482"],
    os: "iOS",
    launchYear: 2021,
    chipset: "A15 Bionic",
    performance: 4,
    displayInches: 6.1,
    displayType: "OLED",
    refreshHz: 60,
    mainCameraMp: 12,
    cameraSummary: "12MP + 12MP ultra-wide",
    frontCameraMp: 12,
    batteryMah: 3240,
    chargingW: 20,
    has5g: true,
    weightG: 173,
    variants: [
      { ramGb: null, storageGb: 128, launchPriceInr: 79900 },
      { ramGb: null, storageGb: 256, launchPriceInr: 89900 },
    ],
    buyPrices: { 128: 24500, 256: 27500 },
  },
  {
    brand: "Apple",
    name: "iPhone 14",
    aliases: ["A2881"],
    os: "iOS",
    launchYear: 2022,
    chipset: "A15 Bionic",
    performance: 4,
    displayInches: 6.1,
    displayType: "OLED",
    refreshHz: 60,
    mainCameraMp: 12,
    cameraSummary: "12MP + 12MP ultra-wide",
    frontCameraMp: 12,
    batteryMah: 3279,
    chargingW: 20,
    has5g: true,
    weightG: 172,
    variants: [
      { ramGb: null, storageGb: 128, launchPriceInr: 79900 },
      { ramGb: null, storageGb: 256, launchPriceInr: 89900 },
    ],
    buyPrices: { 128: 32000, 256: 35000 },
  },
  {
    brand: "Apple",
    name: "iPhone 15",
    aliases: ["A3090"],
    os: "iOS",
    launchYear: 2023,
    chipset: "A16 Bionic",
    performance: 4,
    displayInches: 6.1,
    displayType: "OLED",
    refreshHz: 60,
    mainCameraMp: 48,
    cameraSummary: "48MP + 12MP ultra-wide",
    frontCameraMp: 12,
    batteryMah: 3349,
    chargingW: 20,
    has5g: true,
    weightG: 171,
    variants: [
      { ramGb: null, storageGb: 128, launchPriceInr: 79900 },
      { ramGb: null, storageGb: 256, launchPriceInr: 89900 },
    ],
    buyPrices: { 128: 42000, 256: 46000 },
  },
  {
    brand: "Samsung",
    name: "Galaxy S23",
    aliases: ["SM-S911B", "s23"],
    os: "Android",
    launchYear: 2023,
    chipset: "Snapdragon 8 Gen 2",
    performance: 4,
    displayInches: 6.1,
    displayType: "AMOLED",
    refreshHz: 120,
    mainCameraMp: 50,
    cameraSummary: "50MP + 12MP ultra-wide + 10MP zoom",
    frontCameraMp: 12,
    batteryMah: 3900,
    chargingW: 25,
    has5g: true,
    weightG: 168,
    variants: [
      { ramGb: 8, storageGb: 128, launchPriceInr: 74999 },
      { ramGb: 8, storageGb: 256, launchPriceInr: 79999 },
    ],
    buyPrices: { 128: 28000, 256: 31000 },
  },
  {
    brand: "Samsung",
    name: "Galaxy S21 FE 5G",
    aliases: ["SM-G990E", "s21fe"],
    os: "Android",
    launchYear: 2022,
    chipset: "Exynos 2100",
    performance: 3,
    displayInches: 6.4,
    displayType: "AMOLED",
    refreshHz: 120,
    mainCameraMp: 12,
    cameraSummary: "12MP + 12MP ultra-wide + 8MP zoom",
    frontCameraMp: 32,
    batteryMah: 4500,
    chargingW: 25,
    has5g: true,
    weightG: 177,
    variants: [
      { ramGb: 8, storageGb: 128, launchPriceInr: 54999 },
      { ramGb: 8, storageGb: 256, launchPriceInr: 58999 },
    ],
    buyPrices: { 128: 13500, 256: 15000 },
  },
  {
    brand: "Samsung",
    name: "Galaxy A54 5G",
    aliases: ["SM-A546E", "a54"],
    os: "Android",
    launchYear: 2023,
    chipset: "Exynos 1380",
    performance: 3,
    displayInches: 6.4,
    displayType: "AMOLED",
    refreshHz: 120,
    mainCameraMp: 50,
    cameraSummary: "50MP + 12MP ultra-wide + 5MP macro",
    frontCameraMp: 32,
    batteryMah: 5000,
    chargingW: 25,
    has5g: true,
    weightG: 202,
    variants: [
      { ramGb: 8, storageGb: 128, launchPriceInr: 38999 },
      { ramGb: 8, storageGb: 256, launchPriceInr: 40999 },
    ],
    buyPrices: { 128: 12500, 256: 13500 },
  },
  {
    brand: "Samsung",
    name: "Galaxy A34 5G",
    aliases: ["SM-A346E", "a34"],
    os: "Android",
    launchYear: 2023,
    chipset: "Dimensity 1080",
    performance: 3,
    displayInches: 6.6,
    displayType: "AMOLED",
    refreshHz: 120,
    mainCameraMp: 48,
    cameraSummary: "48MP + 8MP ultra-wide + 5MP macro",
    frontCameraMp: 13,
    batteryMah: 5000,
    chargingW: 25,
    has5g: true,
    weightG: 199,
    variants: [
      { ramGb: 8, storageGb: 128, launchPriceInr: 30999 },
      { ramGb: 8, storageGb: 256, launchPriceInr: 32999 },
    ],
    buyPrices: { 128: 10500, 256: 11500 },
  },
  {
    brand: "Samsung",
    name: "Galaxy M34 5G",
    aliases: ["SM-M346B", "m34"],
    os: "Android",
    launchYear: 2023,
    chipset: "Exynos 1280",
    performance: 2,
    displayInches: 6.5,
    displayType: "AMOLED",
    refreshHz: 120,
    mainCameraMp: 50,
    cameraSummary: "50MP + 8MP ultra-wide + 2MP macro",
    frontCameraMp: 13,
    batteryMah: 6000,
    chargingW: 25,
    has5g: true,
    weightG: 208,
    variants: [
      { ramGb: 6, storageGb: 128, launchPriceInr: 18999 },
      { ramGb: 8, storageGb: 128, launchPriceInr: 20999 },
    ],
    buyPrices: { 128: 7500 },
  },
  {
    brand: "Samsung",
    name: "Galaxy A14 5G",
    aliases: ["SM-A146B", "a14"],
    os: "Android",
    launchYear: 2023,
    chipset: "Exynos 1330",
    performance: 2,
    displayInches: 6.6,
    displayType: "LCD",
    refreshHz: 90,
    mainCameraMp: 50,
    cameraSummary: "50MP + 2MP + 2MP",
    frontCameraMp: 13,
    batteryMah: 5000,
    chargingW: 15,
    has5g: true,
    weightG: 205,
    variants: [
      { ramGb: 4, storageGb: 64, launchPriceInr: 16499 },
      { ramGb: 6, storageGb: 128, launchPriceInr: 18999 },
    ],
    buyPrices: { 64: 4200, 128: 5200 },
  },
  {
    brand: "Redmi",
    name: "Note 12 Pro 5G",
    aliases: ["22101316I", "note12pro", "redmi note 12 pro"],
    os: "Android",
    launchYear: 2023,
    chipset: "Dimensity 1080",
    performance: 3,
    displayInches: 6.67,
    displayType: "AMOLED",
    refreshHz: 120,
    mainCameraMp: 50,
    cameraSummary: "50MP + 8MP ultra-wide + 2MP macro",
    frontCameraMp: 16,
    batteryMah: 5000,
    chargingW: 67,
    has5g: true,
    weightG: 187,
    variants: [
      { ramGb: 6, storageGb: 128, launchPriceInr: 24999 },
      { ramGb: 8, storageGb: 128, launchPriceInr: 26999 },
      { ramGb: 8, storageGb: 256, launchPriceInr: 27999 },
    ],
    buyPrices: { 128: 8000, 256: 9000 },
  },
  {
    brand: "Redmi",
    name: "Note 13 Pro 5G",
    aliases: ["2312DRA50I", "note13pro", "redmi note 13 pro"],
    os: "Android",
    launchYear: 2024,
    chipset: "Snapdragon 7s Gen 2",
    performance: 3,
    displayInches: 6.67,
    displayType: "AMOLED",
    refreshHz: 120,
    mainCameraMp: 200,
    cameraSummary: "200MP + 8MP ultra-wide + 2MP macro",
    frontCameraMp: 16,
    batteryMah: 5100,
    chargingW: 67,
    has5g: true,
    weightG: 187,
    variants: [
      { ramGb: 8, storageGb: 128, launchPriceInr: 25999 },
      { ramGb: 8, storageGb: 256, launchPriceInr: 27999 },
      { ramGb: 12, storageGb: 256, launchPriceInr: 29999 },
    ],
    buyPrices: { 128: 12000, 256: 13500 },
  },
  {
    brand: "Redmi",
    name: "12 5G",
    aliases: ["23076RN4BI", "redmi12"],
    os: "Android",
    launchYear: 2023,
    chipset: "Snapdragon 4 Gen 2",
    performance: 2,
    displayInches: 6.79,
    displayType: "LCD",
    refreshHz: 90,
    mainCameraMp: 50,
    cameraSummary: "50MP + 2MP",
    frontCameraMp: 8,
    batteryMah: 5000,
    chargingW: 18,
    has5g: true,
    weightG: 199,
    variants: [
      { ramGb: 4, storageGb: 128, launchPriceInr: 11999 },
      { ramGb: 6, storageGb: 128, launchPriceInr: 13499 },
      { ramGb: 8, storageGb: 256, launchPriceInr: 15499 },
    ],
    buyPrices: { 128: 5500, 256: 6500 },
  },
  {
    brand: "Redmi",
    name: "13C",
    aliases: ["23100RN82L", "redmi13c"],
    os: "Android",
    launchYear: 2024,
    chipset: "Helio G85",
    performance: 1,
    displayInches: 6.74,
    displayType: "LCD",
    refreshHz: 90,
    mainCameraMp: 50,
    cameraSummary: "50MP + 2MP",
    frontCameraMp: 8,
    batteryMah: 5000,
    chargingW: 18,
    has5g: false,
    weightG: 192,
    variants: [
      { ramGb: 4, storageGb: 128, launchPriceInr: 7999 },
      { ramGb: 6, storageGb: 128, launchPriceInr: 8999 },
    ],
    buyPrices: { 128: 3800 },
  },
  {
    brand: "Poco",
    name: "X5 Pro 5G",
    aliases: ["22101320I", "pocox5pro", "poco x5 pro"],
    os: "Android",
    launchYear: 2023,
    chipset: "Snapdragon 778G",
    performance: 3,
    displayInches: 6.67,
    displayType: "AMOLED",
    refreshHz: 120,
    mainCameraMp: 108,
    cameraSummary: "108MP + 8MP ultra-wide + 2MP macro",
    frontCameraMp: 16,
    batteryMah: 5000,
    chargingW: 67,
    has5g: true,
    weightG: 181,
    variants: [
      { ramGb: 6, storageGb: 128, launchPriceInr: 22999 },
      { ramGb: 8, storageGb: 256, launchPriceInr: 24999 },
    ],
    buyPrices: { 128: 8500, 256: 9500 },
  },
  {
    brand: "OnePlus",
    name: "11R 5G",
    aliases: ["CPH2487", "oneplus11r"],
    os: "Android",
    launchYear: 2023,
    chipset: "Snapdragon 8+ Gen 1",
    performance: 4,
    displayInches: 6.74,
    displayType: "AMOLED",
    refreshHz: 120,
    mainCameraMp: 50,
    cameraSummary: "50MP + 8MP ultra-wide + 2MP macro",
    frontCameraMp: 16,
    batteryMah: 5000,
    chargingW: 100,
    has5g: true,
    weightG: 204,
    variants: [
      { ramGb: 8, storageGb: 128, launchPriceInr: 39999 },
      { ramGb: 16, storageGb: 256, launchPriceInr: 44999 },
    ],
    buyPrices: { 128: 15000, 256: 17000 },
  },
  {
    brand: "OnePlus",
    name: "Nord CE 3 Lite 5G",
    aliases: ["CPH2467", "nordce3lite"],
    os: "Android",
    launchYear: 2023,
    chipset: "Snapdragon 695",
    performance: 2,
    displayInches: 6.72,
    displayType: "LCD",
    refreshHz: 120,
    mainCameraMp: 108,
    cameraSummary: "108MP + 2MP + 2MP",
    frontCameraMp: 16,
    batteryMah: 5000,
    chargingW: 67,
    has5g: true,
    weightG: 195,
    variants: [
      { ramGb: 8, storageGb: 128, launchPriceInr: 19999 },
      { ramGb: 8, storageGb: 256, launchPriceInr: 21999 },
    ],
    buyPrices: { 128: 6800, 256: 7500 },
  },
  {
    brand: "Realme",
    name: "11 Pro 5G",
    aliases: ["RMX3771", "realme11pro"],
    os: "Android",
    launchYear: 2023,
    chipset: "Dimensity 7050",
    performance: 3,
    displayInches: 6.7,
    displayType: "AMOLED",
    refreshHz: 120,
    mainCameraMp: 100,
    cameraSummary: "100MP + 2MP",
    frontCameraMp: 16,
    batteryMah: 5000,
    chargingW: 67,
    has5g: true,
    weightG: 191,
    variants: [
      { ramGb: 8, storageGb: 128, launchPriceInr: 23999 },
      { ramGb: 8, storageGb: 256, launchPriceInr: 24999 },
    ],
    buyPrices: { 128: 8500, 256: 9000 },
  },
  {
    brand: "Vivo",
    name: "T2 5G",
    aliases: ["V2222", "vivot2"],
    os: "Android",
    launchYear: 2023,
    chipset: "Snapdragon 695",
    performance: 2,
    displayInches: 6.38,
    displayType: "AMOLED",
    refreshHz: 90,
    mainCameraMp: 64,
    cameraSummary: "64MP + 2MP",
    frontCameraMp: 16,
    batteryMah: 4500,
    chargingW: 44,
    has5g: true,
    weightG: 172,
    variants: [
      { ramGb: 6, storageGb: 128, launchPriceInr: 18999 },
      { ramGb: 8, storageGb: 128, launchPriceInr: 20999 },
    ],
    buyPrices: { 128: 6000 },
  },
  {
    brand: "iQOO",
    name: "Z7 5G",
    aliases: ["I2207", "iqooz7"],
    os: "Android",
    launchYear: 2023,
    chipset: "Dimensity 920",
    performance: 3,
    displayInches: 6.38,
    displayType: "AMOLED",
    refreshHz: 90,
    mainCameraMp: 64,
    cameraSummary: "64MP + 2MP",
    frontCameraMp: 16,
    batteryMah: 4500,
    chargingW: 44,
    has5g: true,
    weightG: 173,
    variants: [
      { ramGb: 6, storageGb: 128, launchPriceInr: 18999 },
      { ramGb: 8, storageGb: 128, launchPriceInr: 19999 },
    ],
    buyPrices: { 128: 6500 },
  },
  {
    brand: "Google",
    name: "Pixel 7",
    aliases: ["GVU6C", "pixel7"],
    os: "Android",
    launchYear: 2022,
    chipset: "Google Tensor G2",
    performance: 4,
    displayInches: 6.3,
    displayType: "OLED",
    refreshHz: 90,
    mainCameraMp: 50,
    cameraSummary: "50MP + 12MP ultra-wide",
    frontCameraMp: 11,
    batteryMah: 4355,
    chargingW: 21,
    has5g: true,
    weightG: 197,
    variants: [{ ramGb: 8, storageGb: 128, launchPriceInr: 59999 }],
    buyPrices: { 128: 14500 },
  },
  {
    brand: "Motorola",
    name: "Edge 40 Neo",
    aliases: ["XT2307-3", "edge40neo"],
    os: "Android",
    launchYear: 2023,
    chipset: "Dimensity 7030",
    performance: 3,
    displayInches: 6.55,
    displayType: "pOLED",
    refreshHz: 144,
    mainCameraMp: 50,
    cameraSummary: "50MP + 13MP ultra-wide",
    frontCameraMp: 32,
    batteryMah: 5000,
    chargingW: 68,
    has5g: true,
    weightG: 170,
    variants: [
      { ramGb: 8, storageGb: 128, launchPriceInr: 23999 },
      { ramGb: 12, storageGb: 256, launchPriceInr: 25999 },
    ],
    buyPrices: { 128: 8000, 256: 9000 },
  },
  {
    brand: "Nothing",
    name: "Phone (2a)",
    aliases: ["A142", "phone 2a", "nothing2a"],
    os: "Android",
    launchYear: 2024,
    chipset: "Dimensity 7200 Pro",
    performance: 3,
    displayInches: 6.7,
    displayType: "AMOLED",
    refreshHz: 120,
    mainCameraMp: 50,
    cameraSummary: "50MP + 50MP ultra-wide",
    frontCameraMp: 32,
    batteryMah: 5000,
    chargingW: 45,
    has5g: true,
    weightG: 190,
    variants: [
      { ramGb: 8, storageGb: 128, launchPriceInr: 23999 },
      { ramGb: 8, storageGb: 256, launchPriceInr: 25999 },
    ],
    buyPrices: { 128: 10500, 256: 11500 },
  },
];

export type SeedListing = {
  model: string;
  ramGb: number | null;
  storageGb: number;
  color: string;
  hex: string;
  grade: "A" | "B" | "C";
  batteryHealth: number | null;
  batteryNote?: string;
  priceInr: number;
  previousPriceInr?: number;
  costInr: number;
  hasBox?: boolean;
  hasCharger?: boolean;
  hasBill?: boolean;
  shopTags?: string[];
  notesEn?: string;
  notesTe?: string;
  failed?: string[];
  status?: "available" | "reserved" | "sold" | "draft";
  daysAgo: number;
  featured?: boolean;
  soldDaysAgo?: number;
  warrantyMonths?: number;
  camera: "square" | "pill" | "bar" | "island";
};

export const SEED_LISTINGS: SeedListing[] = [
  {
    model: "iPhone 13",
    ramGb: null,
    storageGb: 128,
    color: "Midnight",
    hex: "#232a36",
    grade: "A",
    batteryHealth: 89,
    priceInr: 31999,
    costInr: 26500,
    hasBox: true,
    hasBill: true,
    shopTags: ["camera"],
    daysAgo: 1,
    featured: true,
    camera: "square",
    notesEn: "Used with a cover and screen guard from day one. Face ID works.",
    notesTe: "మొదటి రోజు నుంచి కవర్, స్క్రీన్ గార్డ్‌తో వాడారు. ఫేస్ ఐడీ పని చేస్తుంది.",
  },
  {
    model: "Redmi Note 13 Pro 5G",
    ramGb: 8,
    storageGb: 256,
    color: "Coral Purple",
    hex: "#9b7fc4",
    grade: "A",
    batteryHealth: null,
    priceInr: 17999,
    previousPriceInr: 18999,
    costInr: 14000,
    hasBox: true,
    hasBill: true,
    hasCharger: true,
    shopTags: ["camera"],
    daysAgo: 3,
    camera: "pill",
  },
  {
    model: "OnePlus 11R 5G",
    ramGb: 8,
    storageGb: 128,
    color: "Sonic Black",
    hex: "#1e2126",
    grade: "A",
    batteryHealth: null,
    priceInr: 21999,
    costInr: 17500,
    hasBox: true,
    hasCharger: true,
    shopTags: ["gaming"],
    daysAgo: 2,
    camera: "island",
  },
  {
    model: "iPhone 12",
    ramGb: null,
    storageGb: 64,
    color: "Blue",
    hex: "#34568b",
    grade: "B",
    batteryHealth: 84,
    priceInr: 21499,
    costInr: 18000,
    shopTags: ["students"],
    daysAgo: 4,
    camera: "square",
    notesEn: "Light marks on the side frame. Screen is perfect.",
    notesTe: "సైడ్ ఫ్రేమ్‌పై చిన్న గుర్తులు. స్క్రీన్ బాగుంది.",
  },
  {
    model: "Galaxy S23",
    ramGb: 8,
    storageGb: 256,
    color: "Phantom Black",
    hex: "#25262b",
    grade: "A",
    batteryHealth: null,
    batteryNote: "Battery lasts a full day",
    priceInr: 38999,
    costInr: 33000,
    hasBox: true,
    hasBill: true,
    shopTags: ["camera"],
    daysAgo: 5,
    camera: "bar",
  },
  {
    model: "iPhone 14",
    ramGb: null,
    storageGb: 128,
    color: "Purple",
    hex: "#c7b9e2",
    grade: "A",
    batteryHealth: 93,
    priceInr: 41999,
    costInr: 36000,
    hasBox: true,
    hasBill: true,
    daysAgo: 6,
    camera: "square",
  },
  {
    model: "Galaxy M34 5G",
    ramGb: 6,
    storageGb: 128,
    color: "Midnight Blue",
    hex: "#233358",
    grade: "A",
    batteryHealth: null,
    priceInr: 10999,
    costInr: 8200,
    hasBox: true,
    shopTags: ["parents"],
    daysAgo: 8,
    camera: "bar",
  },
  {
    model: "Poco X5 Pro 5G",
    ramGb: 8,
    storageGb: 256,
    color: "Yellow",
    hex: "#f0c42b",
    grade: "B",
    batteryHealth: null,
    priceInr: 13999,
    costInr: 11000,
    hasCharger: true,
    shopTags: ["gaming"],
    daysAgo: 9,
    camera: "pill",
  },
  {
    model: "Pixel 7",
    ramGb: 8,
    storageGb: 128,
    color: "Obsidian",
    hex: "#2b2c30",
    grade: "B",
    batteryHealth: 86,
    priceInr: 19999,
    costInr: 16000,
    shopTags: ["camera"],
    daysAgo: 10,
    camera: "bar",
    notesEn: "Small scratch near the camera bar. No effect on photos.",
    notesTe: "కెమెరా బార్ దగ్గర చిన్న గీత. ఫోటోలపై ప్రభావం లేదు.",
  },
  {
    model: "Redmi 12 5G",
    ramGb: 6,
    storageGb: 128,
    color: "Moonstone Silver",
    hex: "#cdd2d9",
    grade: "A",
    batteryHealth: null,
    priceInr: 8499,
    costInr: 6200,
    hasBox: true,
    hasCharger: true,
    hasBill: true,
    shopTags: ["parents"],
    daysAgo: 11,
    camera: "pill",
  },
  {
    model: "Nothing Phone (2a)",
    ramGb: 8,
    storageGb: 128,
    color: "White",
    hex: "#eceef0",
    grade: "A",
    batteryHealth: null,
    priceInr: 15499,
    costInr: 12500,
    hasBox: true,
    status: "reserved",
    daysAgo: 7,
    camera: "island",
  },
  {
    model: "Galaxy A54 5G",
    ramGb: 8,
    storageGb: 128,
    color: "Awesome Lime",
    hex: "#d3e59c",
    grade: "B",
    batteryHealth: null,
    priceInr: 16499,
    costInr: 13500,
    daysAgo: 12,
    camera: "pill",
  },
  {
    model: "Realme 11 Pro 5G",
    ramGb: 8,
    storageGb: 256,
    color: "Sunrise Beige",
    hex: "#e4cfb0",
    grade: "A",
    batteryHealth: null,
    priceInr: 12999,
    costInr: 10000,
    hasBox: true,
    hasCharger: true,
    daysAgo: 13,
    camera: "island",
  },
  {
    model: "OnePlus Nord CE 3 Lite 5G",
    ramGb: 8,
    storageGb: 128,
    color: "Pastel Lime",
    hex: "#c6e19c",
    grade: "B",
    batteryHealth: null,
    priceInr: 9999,
    costInr: 7500,
    hasCharger: true,
    shopTags: ["students"],
    daysAgo: 14,
    camera: "pill",
  },
  {
    model: "Motorola Edge 40 Neo",
    ramGb: 8,
    storageGb: 128,
    color: "Soothing Sea",
    hex: "#7fb3b2",
    grade: "B",
    batteryHealth: null,
    priceInr: 12499,
    costInr: 9800,
    hasBox: true,
    daysAgo: 15,
    camera: "bar",
  },
  {
    model: "iPhone 11",
    ramGb: null,
    storageGb: 64,
    color: "White",
    hex: "#eeeeec",
    grade: "B",
    batteryHealth: 81,
    priceInr: 16999,
    costInr: 13500,
    hasBox: true,
    shopTags: ["parents"],
    daysAgo: 16,
    camera: "square",
  },
  {
    model: "Galaxy A14 5G",
    ramGb: 4,
    storageGb: 64,
    color: "Dark Red",
    hex: "#7b2332",
    grade: "C",
    batteryHealth: null,
    priceInr: 6499,
    costInr: 4600,
    shopTags: ["students"],
    daysAgo: 18,
    camera: "pill",
    failed: ["vibration"],
    notesEn: "Visible scratches on the back. Vibration motor is weak, everything else works.",
    notesTe: "వెనుక భాగంలో గీతలు కనిపిస్తాయి. వైబ్రేషన్ బలహీనంగా ఉంది, మిగతావన్నీ పని చేస్తాయి.",
  },
  {
    model: "Vivo T2 5G",
    ramGb: 6,
    storageGb: 128,
    color: "Velocity Wave",
    hex: "#3b69ad",
    grade: "C",
    batteryHealth: null,
    priceInr: 7999,
    costInr: 5900,
    hasCharger: true,
    daysAgo: 20,
    camera: "bar",
  },
  {
    model: "Galaxy A34 5G",
    ramGb: 8,
    storageGb: 128,
    color: "Awesome Graphite",
    hex: "#3a3b40",
    grade: "A",
    batteryHealth: null,
    priceInr: 14499,
    costInr: 11500,
    hasBox: true,
    status: "sold",
    daysAgo: 12,
    soldDaysAgo: 3,
    camera: "pill",
  },
  {
    model: "iQOO Z7 5G",
    ramGb: 8,
    storageGb: 128,
    color: "Pacific Night",
    hex: "#26324d",
    grade: "B",
    batteryHealth: null,
    priceInr: 9499,
    costInr: 7200,
    status: "sold",
    daysAgo: 20,
    soldDaysAgo: 9,
    camera: "bar",
  },
];
